
module.exports = {
    username: 'training_nodejs',
    password: 'a123456789',
    //db articles
    database_articles: 'nodejs_items',
    col_items: 'items',
    col_groups: 'groups',
    col_users: 'users',
    col_category: 'category',
    col_articles: 'articles',
    col_rss: 'rss',
    col_contact: 'contact',
    col_config: 'config',
    // db products
    database_products: 'shop',
    col_product_category: 'category',
    col_brand: 'brand',
    col_product: 'product',
    col_clothing_category: 'clothing-category',
    col_clothing: 'clothing',
    col_slider: 'slider',
    col_banner: 'banner',
    col_subscribe: 'subscribe',
    col_order: 'order',
    col_promo: 'promo',
    col_shipping: 'shipping',
    col_accessory_category: 'accessory-category',
    col_accessory: 'accessory',
    col_event: 'event',
};