
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_SPECIAL_SUCCESS: 'Cập nhật special thành công',
    CHANGE_SPECIAL_MULTI_SUCCESS: 'Có %d phần tử được cập nhật special thành công',
    CHANGE_TRENDING_SUCCESS: 'Cập nhật trending thành công',
    CHANGE_TRENDING_MULTI_SUCCESS: 'Có %d phần tử được cập nhật trending thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    CHANGE_FEE_SUCCESS: 'Cập nhật phí vận chuyển thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    ERROR_NAME: 'Chiều dài từ %d đến %d ký tự',
    ERROR_EMAIL: 'Chiều dài từ %d đến %d ký tự',
    ERROR_PHONE: 'Chiều dài từ %d đến %d ký tự',
    ERROR_MESSAGE: 'Chiều dài từ %d đến %d ký tự',
    ERROR_SLUG: 'Chiều dài từ %d đến %d ký tự',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Phải là một giá trị khác rỗng',
    ERROR_GROUP: 'Phải chọn một nhóm nhất định',
    ERROR_GROUP_ACP: 'Phải chọn một giá trị khác rỗng',
    CHANGE_GROUP_ACP_SUCCESS: 'Cập nhật group ACP thành công',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp',
    ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ',
    ERROR_CATEGORY: 'Phải chọn một Category nhất định',
    ERROR_LOGIN: 'Thông tin đăng nhập không chính xác',
    ADD_CONTACT_SUCCESS: 'Thông tin đã được gửi đi!',
    ERROR_PRICE: 'Giá tiền phải lớn hơn %d',
    ERROR_QUANTITY: 'Số lượng phải lớn hơn %d',
    ERROR_BRAND: 'Chiều dài khác rỗng',
    SUBSCRIBE_SUCCESS: 'Sign up success',
    ERROR_SIZE: 'Size phải khác rỗng',
    ERROR_COLOR: 'Color phải khác rỗng',
    ADD_REVIEW_SUCCESS: 'Your review add success',
    FAVORITE_SUCCESS: 'Favorite success'
};