
module.exports = {
    prefixAdmin: 'admin',
    prefixBlog: 'blog',
    prefixShop: '',
    env: 'dev', // production dev
    format_date: 'DD-MM-YYYY',
    format_date_2: 'MMMM Do YYYY, h:mm:ss a',
    status_value: [
        {name: 'Choose Status', id: 'allValue'},
        {name: 'Active', id: 'active'},
        {name: 'InActive', id: 'inactive'},
    ],
    radio_object: [
		{value: 'yes', name: 'Yes'},
		{value: 'no', name: 'No'}
	],
    orders_state_value: [ // chờ xác nhận, chờ lấy hàng, đang giao, đã giao, đã hủy
        {id: 'accepted', name: 'Accepted'},
        {id: 'in-progress', name: 'In progress'},
        {id: 'shipped', name: 'Shipped'},
        {id: 'delivered', name: 'Delivered'},
        {id: 'completed', name: 'Completed'},
	],
    status_contact: [
        {name: 'Not contacted', id: 'not-contacted'},
        {name: 'Contacted', id: 'contacted'},
    ],
    VietNamProvince: [
        { "code":"89" , "name":"An Giang"},
        { "code":"77" , "name":"Bà Rịa - Vũng Tàu"},
        { "code":"24" , "name":"Bắc Giang"},
        { "code":"6" , "name":"Bắc Kạn"},
        { "code":"95" , "name":"Bạc Liêu"},
        { "code":"27" , "name":"Bắc Ninh"},
        { "code":"83" , "name":"Bến Tre"},
        { "code":"52" , "name":"Bình Định"},
        { "code":"74" , "name":"Bình Dương"},
        { "code":"70" , "name":"Bình Phước"},
        { "code":"60" , "name":"Bình Thuận"},
        { "code":"96" , "name":"Cà Mau"},
        { "code":"92" , "name":"Cần Thơ"},
        { "code":"4" , "name":"Cao Bằng"},
        { "code":"48" , "name":"Đà Nẵng"},
        { "code":"66" , "name":"Đắk Lắk"},
        { "code":"67" , "name":"Đắk Nông"},
        { "code":"11" , "name":"Điện Biên"},
        { "code":"75" , "name":"Đồng Nai"},
        { "code":"87" , "name":"Đồng Tháp"},
        { "code":"64" , "name":"Gia Lai"},
        { "code":"2" , "name":"Hà Giang"},
        { "code":"35" , "name":"Hà Nam"},
        { "code":"1" , "name":"Hà Nội"},
        { "code":"42" , "name":"Hà Tĩnh"},
        { "code":"30" , "name":"Hải Dương"},
        { "code":"31" , "name":"Hải Phòng"},
        { "code":"93" , "name":"Hậu Giang"},
        { "code":"79" , "name":"Hồ Chí Minh"},
        { "code":"17" , "name":"Hòa Bình"},
        { "code":"33" , "name":"Hưng Yên"},
        { "code":"56" , "name":"Khánh Hòa"},
        { "code":"91" , "name":"Kiên Giang"},
        { "code":"62" , "name":"Kon Tum"},
        { "code":"12" , "name":"Lai Châu"},
        { "code":"68" , "name":"Lâm Đồng"},
        { "code":"20" , "name":"Lạng Sơn"},
        { "code":"10" , "name":"Lào Cai"},
        { "code":"80" , "name":"Long An"},
        { "code":"36" , "name":"Nam Định"},
        { "code":"40" , "name":"Nghệ An"},
        { "code":"37" , "name":"Ninh Bình"},
        { "code":"58" , "name":"Ninh Thuận"},
        { "code":"25" , "name":"Phú Thọ"},
        { "code":"54" , "name":"Phú Yên"},
        { "code":"44" , "name":"Quảng Bình"},
        { "code":"49" , "name":"Quảng Nam"},
        { "code":"51" , "name":"Quảng Ngãi"},
        { "code":"22" , "name":"Quảng Ninh"},
        { "code":"45" , "name":"Quảng Trị"},
        { "code":"94" , "name":"Sóc Trăng"},
        { "code":"14" , "name":"Sơn La"},
        { "code":"72" , "name":"Tây Ninh"},
        { "code":"34" , "name":"Thái Bình"},
        { "code":"19" , "name":"Thái Nguyên"},
        { "code":"38" , "name":"Thanh Hóa"},
        { "code":"46" , "name":"Thừa Thiên Huế"},
        { "code":"82" , "name":"Tiền Giang"},
        { "code":"84" , "name":"Trà Vinh"},
        { "code":"8" , "name":"Tuyên Quang"},
        { "code":"86" , "name":"Vĩnh Long"},
        { "code":"26" , "name":"Vĩnh Phúc"},
        { "code":"15" , "name":"Yên Bái"},
    ],
    style_banner_value: [
        {name: 'Choose style slider', id: 'allValue'},
        {name: 'Dark Banner', id: 'ps-banner--black'},
        {name: 'Light Banner', id: 'ps-banner--white'},
    ],
    product_value: [
        {name: 'Choose Type of Product', id: 'allValue'},
        {name: 'Shoes', id: 'shoes'},
        {name: 'Clothing', id: 'clothing'},
        {name: 'Accessory', id: 'accessory'},
    ],
    color_value: [
        {name: 'Black', id: 'black'},
        {name: 'Blue', id: 'blue'},
        {name: 'White', id: 'white'},
        {name: 'Grey', id: 'grey'},
        {name: 'Green', id: 'green'},
        {name: 'Yellow', id: 'yellow'},
        {name: 'Red', id: 'red'},
        {name: 'Pink', id: 'pink'},
        {name: 'Silver', id: 'silver'},
        {name: 'Purple', id: 'purple'},
    ],
    size_shoe_value: [
        {name: '3', id: '3'},
        {name: '3.5', id: '3'},
        {name: '4', id: '4'},
        {name: '4.5', id: '4.5'},
        {name: '5', id: '5'},
        {name: '5.5', id: '5.5'},
        {name: '6', id: '6'},
        {name: '6.5', id: '6.5'},
        {name: '7', id: '7'},
        {name: '7.5', id: '7.5'},
        {name: '8', id: '8'},
        {name: '8.5', id: '8.5'},
        {name: '9', id: '9'},
        {name: '9.5', id: '9.5'},
        {name: '10', id: '10'},
        {name: '10.5', id: '10.5'},
        {name: '11', id: '11'},
        {name: '11.5', id: '11.5'},
        {name: '12', id: '12'},
        {name: '12.5', id: '12.5'},
        {name: '13', id: '13'},
        {name: '13.5', id: '13.5'},
        {name: '14', id: '14'},
        {name: '14.5', id: '14.5'},
        {name: '15', id: '15'},
    ],
    size_clothing_value: [
        {name: 'S', id: 's'},
        {name: 'M', id: 'm'},
        {name: 'L', id: 'l'},
        {name: 'XL', id: 'xl'},
        {name: '2XL', id: '2xl'},
    ]
}