
module.exports = {
    prefixAdmin: 'admin',
    prefixBlog: 'blog',
    prefixShop: '',
    env: 'dev', // production dev
    format_date: 'DD-MM-YYYY',
    format_date_2: 'MMMM Do YYYY, h:mm:ss a',
    status_value: [
        {name: 'Choose Status', id: 'allValue'},
        {name: 'Active', id: 'active'},
        {name: 'InActive', id: 'inactive'},
    ],
    radio_object: [
		{value: 'yes', name: 'Yes'},
		{value: 'no', name: 'No'}
	],
    orders_state_value: [ // chờ xác nhận, chờ lấy hàng, đang giao, đã giao, đã hủy
        {id: 'accepted', name: 'Accepted'},
        {id: 'in-progress', name: 'In progress'},
        {id: 'shipped', name: 'Shipped'},
        {id: 'delivered', name: 'Delivered'},
        {id: 'completed', name: 'Completed'},
	],
    status_contact: [
        {name: 'Not contacted', id: 'not-contacted'},
        {name: 'Contacted', id: 'contacted'},
    ],
    VietNamProvince: [
        { "code":"89" , "name":"An Giang"},
        { "code":"77" , "name":"Bà Rịa - Vũng Tàu"},
        { "code":"24" , "name":"Bắc Giang"},
        { "code":"6" , "name":"Bắc Kạn"},
        { "code":"95" , "name":"Bạc Liêu"},
        { "code":"27" , "name":"Bắc Ninh"},
        { "code":"83" , "name":"Bến Tre"},
        { "code":"52" , "name":"Bình Định"},
        { "code":"74" , "name":"Bình Dương"},
        { "code":"70" , "name":"Bình Phước"},
        { "code":"60" , "name":"Bình Thuận"},
        { "code":"96" , "name":"Cà Mau"},
        { "code":"92" , "name":"Cần Thơ"},
        { "code":"4" , "name":"Cao Bằng"},
        { "code":"48" , "name":"Đà Nẵng"},
        { "code":"66" , "name":"Đắk Lắk"},
        { "code":"67" , "name":"Đắk Nông"},
        { "code":"11" , "name":"Điện Biên"},
        { "code":"75" , "name":"Đồng Nai"},
        { "code":"87" , "name":"Đồng Tháp"},
        { "code":"64" , "name":"Gia Lai"},
        { "code":"2" , "name":"Hà Giang"},
        { "code":"35" , "name":"Hà Nam"},
        { "code":"1" , "name":"Hà Nội"},
        { "code":"42" , "name":"Hà Tĩnh"},
        { "code":"30" , "name":"Hải Dương"},
        { "code":"31" , "name":"Hải Phòng"},
        { "code":"93" , "name":"Hậu Giang"},
        { "code":"79" , "name":"Hồ Chí Minh"},
        { "code":"17" , "name":"Hòa Bình"},
        { "code":"33" , "name":"Hưng Yên"},
        { "code":"56" , "name":"Khánh Hòa"},
        { "code":"91" , "name":"Kiên Giang"},
        { "code":"62" , "name":"Kon Tum"},
        { "code":"12" , "name":"Lai Châu"},
        { "code":"68" , "name":"Lâm Đồng"},
        { "code":"20" , "name":"Lạng Sơn"},
        { "code":"10" , "name":"Lào Cai"},
        { "code":"80" , "name":"Long An"},
        { "code":"36" , "name":"Nam Định"},
        { "code":"40" , "name":"Nghệ An"},
        { "code":"37" , "name":"Ninh Bình"},
        { "code":"58" , "name":"Ninh Thuận"},
        { "code":"25" , "name":"Phú Thọ"},
        { "code":"54" , "name":"Phú Yên"},
        { "code":"44" , "name":"Quảng Bình"},
        { "code":"49" , "name":"Quảng Nam"},
        { "code":"51" , "name":"Quảng Ngãi"},
        { "code":"22" , "name":"Quảng Ninh"},
        { "code":"45" , "name":"Quảng Trị"},
        { "code":"94" , "name":"Sóc Trăng"},
        { "code":"14" , "name":"Sơn La"},
        { "code":"72" , "name":"Tây Ninh"},
        { "code":"34" , "name":"Thái Bình"},
        { "code":"19" , "name":"Thái Nguyên"},
        { "code":"38" , "name":"Thanh Hóa"},
        { "code":"46" , "name":"Thừa Thiên Huế"},
        { "code":"82" , "name":"Tiền Giang"},
        { "code":"84" , "name":"Trà Vinh"},
        { "code":"8" , "name":"Tuyên Quang"},
        { "code":"86" , "name":"Vĩnh Long"},
        { "code":"26" , "name":"Vĩnh Phúc"},
        { "code":"15" , "name":"Yên Bái"},
    ],
    style_banner_value: [
        {name: 'Choose style slider', id: 'allValue'},
        {name: 'Dark Banner', id: 'ps-banner--black'},
        {name: 'Light Banner', id: 'ps-banner--white'},
    ],
}